"""
Django settings for Community_Sync project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os
import dj_database_url  # REQUIRED: Helper for Supabase/PostgreSQL connection
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-fallback-key-do-not-use-in-production"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = ["*"]  # Allowed all for development purposes


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Custom Apps
    "apps.accounts",
    "apps.announcements",
    "apps.communities",
    "apps.dashboard",
    "apps.maintenance",
    "apps.payments",
    "apps.visitors",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Community_Sync.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Updated DIRS to look for a 'templates' folder in the root project directory
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Community_Sync.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# -------------------------------------------------------------------------
# SUPABASE CONFIGURATION
# Replace the string below with your actual Connection String (URI) from Supabase
# Go to Supabase -> Project Settings -> Database -> Connection String -> URI
# It looks like: postgres://postgres.[ref]:[password]@aws-0-[region].pooler.supabase.com:6543/postgres
# -------------------------------------------------------------------------

DATABASE_URL = os.getenv("DATABASE_URL")  # Read from .env

# If a remote DATABASE_URL (e.g. Supabase/Postgres) is provided, use it.
# Otherwise fall back to a local SQLite database for development.
if DATABASE_URL:
    DATABASES = {"default": dj_database_url.config(default=DATABASE_URL, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Custom User Model
# This tells Django to use the model we created in apps/accounts/models.py instead of the default User
AUTH_USER_MODEL = "accounts.CustomUser"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Login Redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "resident_home"  # Default fallback if custom logic fails
LOGOUT_REDIRECT_URL = "login"

# Supabase project URL (used to verify access tokens server-side)
SUPABASE_URL = os.getenv("SUPABASE_URL", "https://rjxislnrsgmxfyvqwgfh.supabase.co")
