# Generated by Django 5.2.6 on 2026-04-17 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bill_fee_type_name_alter_bill_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrule',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='fee_type',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='fee_type_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='billingrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='billingrule',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.DeleteModel(
            name='FeeType',
        ),
    ]
