# Generated by Django 5.2.6 on 2026-04-07 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Can be full name or nickname', max_length=255)),
                ('license_plate', models.CharField(blank=True, max_length=50, null=True)),
                ('home_number', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('visit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('arrived', 'Arrived'), ('completed', 'Completed')], default='expected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'security'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitors', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visitor_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='visitors.visitor')),
            ],
        ),
    ]
