# Generated by Django 5.2.6 on 2026-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_id_alter_visitorimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('expected', 'Expected'), ('arrived', 'Arrived'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='expected', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitorimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
